(defparameter *house* '((walls 		(mortar 	(cement)
												(water)
												(sand))
									(bricks))
						(windows	(glass)
									(frame)
									(curtains))
						(roof		(shingles)
									(chimney))))